spring:
  application:
    name: warehouse-service
  datasource:
    url: jdbc:mariadb://${DB_URL:db}:3306/warehouse
    username: root
    password: pw
  jpa:
    #show-sql: true
    generate-ddl: true
    properties.hibernate.dialect: org.hibernate.dialect.MariaDBDialect
    hibernate.ddl-auto: update
